# Path to Caffe repository
CAFFE_PATH: /Users/vfomin/Documents/ML/caffe-master_42cd785/

# Path to image dataset
#DATASET_PATH: /Users/vfomin/Documents/ML/Pascal_VOC_2011/VOCdevkit/VOC2011/JPEGImages/
DATASET_PATH: /Users/vfomin/Documents/ML/caffe-master_42cd785/examples/images/
# Path to labels file
LABELS_FILE_PATH: /Users/vfomin/Documents/ML/caffe-master_42cd785/data/ilsvrc12/synset_words.txt

# List of available nets: [ [<model_label>, <model_path>, <weights_path or ''>, <mean_image_path or ''>], ... ]
NETS_LIST: {
  'caffe_net': ['bvlc_reference_caffenet/deploy.prototxt', 'bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel', 'ilsvrc12/imagenet_mean.binaryproto'],
  'vgg16': ['vgg/VGG_ILSVRC_16_layers_deploy.prototxt', 'vgg/VGG_ILSVRC_16_layers.caffemodel', 'ilsvrc12/imagenet_mean.binaryproto'],
  'resnet50': ['ResNet/ResNet-50-deploy.prototxt', 'ResNet/ResNet-50-model.caffemodel', 'ilsvrc12/imagenet_mean.binaryproto']
}

# List with paths to models
MODELS_PATH_LIST: [
  /Users/vfomin/Documents/ML/caffe-master_42cd785/models,
  /Users/vfomin/Documents/ML/fcn/voc-fcn16s
]

# List with paths to weights
RESOURCES_PATH_LIST: [
  /Users/vfomin/Documents/ML/caffe-master_42cd785/models,
  /Users/vfomin/Documents/ML/caffe-master_42cd785/data,
  /Users/vfomin/Documents/ML/fcn/voc-fcn16s
]


# Use CPU instead of GPU
USE_CPU: false



